import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./pages/composants/header";
import Accueil from "./pages/accueil/accueil";
import Footer from "./pages/composants/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <Accueil />
      <Footer />
    </>
  );
}
